projects:
  amplifyDatasource:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - schema
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
